FROM python:3.12

WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src

CMD ["flask", "--app", "src.presentation.webui", "run", "--host", "0.0.0.0"]
